import type { NextPage } from 'next'
import Head from 'next/head'
import ItemContainer from '../components/ItemContainer'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import ScoreBoard from '../components/ScoreBoard'
import Modal from '../components/Modal'
import { useState } from 'react'

const Home: NextPage = () => {
  const [showModal, setShowModal] = useState(false);
  
  const handleItemClick = (itemName: string) => {
    console.log('itemName', itemName);
  }

  const handleModalClose = () => {
    console.log('works');
    
    setShowModal(false)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Rock, Paper, Scissors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.logo_container}>
          <div className={styles.logo}>
          <Image src="/images/logo.svg" alt="Game Logo" width={80} height={40} />
          </div>
          <div className={styles.scoreboard}>
            <ScoreBoard />
          </div>
        </div>
        <div className={styles.double}>
        <ItemContainer handleClick={handleItemClick} itemName='paper' />
        <ItemContainer handleClick={handleItemClick} itemName='scissors' />
        </div>
        <div className={styles.single}>
        
        <ItemContainer handleClick={handleItemClick} itemName='rock' />
        </div>
        <div className={styles.single}>
          <button onClick={() => setShowModal(true)} className={styles.outlined_button}>RULES</button>
        </div>
        <Modal title="My Modal" onClose={handleModalClose} show={showModal} />
      </main>
    </div>
  )
}

export default Home
