import type { NextPage } from 'next'
import Head from 'next/head'
import ItemContainer from '../components/ItemContainer'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import ScoreBoard from '../components/ScoreBoard'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rock, Paper, Scissors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.logo_container}>
          <div className={styles.logo}>
          <Image src="/images/logo.svg" alt="Game Logo" width={80} height={40} />
          </div>
          <div className={styles.scoreboard}>
            <ScoreBoard />
          </div>
        </div>
        <div className={styles.double}>
        <ItemContainer itemName='rock' />
        <ItemContainer itemName='paper' />
        </div>
        <div className={styles.single}>
        <ItemContainer itemName='scissors' />
        </div>
      </main>
    </div>
  )
}

export default Home
