import type { NextPage } from 'next'
import Head from 'next/head'
import ItemContainer from '../components/ItemContainer'
import Rock from '../components/Rock'
import styles from '../styles/Home.module.css'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rock, Paper, Scissors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.logo_container}>
        <Image src="/images/logo.svg" alt="Rock Icon" width={52} height={52} />
        </div>
        <ItemContainer itemName='rock'>
          <Rock />
        </ItemContainer>
      </main>
    </div>
  )
}

export default Home
